module.exports = {
  OK_STATUS_CODE: 200,
  CREATED_STATUS_CODE: 201,
  BAD_REQUEST_STATUS_CODE: 400,
  NOT_FOUND_STATUS_CODE: 404,
  INTERNAL_SERVER_ERROR_STATUS_CODE: 500,
  CONFLICT_STATUS_CODE:409,
  UNAUTHORIZED_STATUS_CODE:401,
  FORBIDDEN_STATUS_CODE:403,  
};
